/**
 * API Mediatheque
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Exemplaire } from './exemplaire';


export interface Emprunt { 
    id?: number;
    dateEmprunt?: string;
    dateRetour?: string;
    exemplaires?: Array<Exemplaire>;
}

